=== GangaHPillai/CIA1-LAB/EMS.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Company" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Company" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Employee">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="empname" type="xs:string" minOccurs="0" />
              <xs:element name="empage" type="xs:integer" minOccurs="0" />
              <xs:element name="empsalary" type="MySalary" minOccurs="0" />
              <xs:element name="empemail" type="xs:string" minOccurs="0" />
              <xs:element name="empphone" type="xs:integer" minOccurs="0" />
              <xs:element name="empdesignation" type="xs:string" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="MySalary">
  <xs:restriction base="xs:integer">
  <xs:maxExclusive value="200000"></xs:maxExclusive>
  <xs:minExclusive value="50000"></xs:minExclusive>
  </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== GangaHPillai/CIA1-LAB/EMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EMS.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EMS.xsd">
<Employee ID="D101">
    <empname>Anita</empname>
	<empage>50</empage>
    <empsalary>50000</empsalary>
    <empemail>anita123@gmail.com</empemail>
    <empphone>9656274790</empphone>
    <empdesignation>Developer</empdesignation>
</Employee>

<Employee ID="A102">
	<empname>Ravi</empname>
	<empage>51</empage>
	<empsalary>112000</empsalary>
	<empemail>ravi663@gmail.com</empemail>
	<empphone>8823602721</empphone>
	<empdesignation>Associate Project Manager</empdesignation>
  </Employee>
  
  <Employee ID="T103">
    <empname>Nitya</empname>
	<empage>30</empage>
    <empsalary>60000</empsalary>
    <empemail>nitya2657@gmail.com</empemail>
    <empphone>8236329820</empphone>
    <empdesignation>Team Leader</empdesignation>
  </Employee>
  
  <Employee ID="M104">
    <empname>Deeksha</empname>
	<empage>41</empage>
    <empsalary>150000</empsalary>
    <empemail>mddeeksha@gmail.com</empemail>
    <empphone>8535430166</empphone>
    <empdesignation>Manager</empdesignation>
  </Employee>
</Company>
